# Generated by Django 6.0 on 2026-07-15 10:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedPersonType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('name', models.CharField(help_text='Type name (e.g., Employee, Director, Agent)', max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Description of this person type', verbose_name='description')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('is_default', models.BooleanField(default=False, help_text='Default type for new associated persons', verbose_name='default')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'associated person type',
                'verbose_name_plural': 'associated person types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssociatedPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='middle name')),
                ('national_id', models.CharField(blank=True, help_text='National identity card number', max_length=50, null=True, unique=True, verbose_name='national ID')),
                ('passport_number', models.CharField(blank=True, help_text='Passport number', max_length=50, null=True, unique=True, verbose_name='passport number')),
                ('employee_id', models.CharField(blank=True, help_text='Internal employee identification number', max_length=50, null=True, unique=True, verbose_name='employee ID')),
                ('job_title', models.CharField(blank=True, help_text='Current job title/position', max_length=150, verbose_name='job title')),
                ('department', models.CharField(blank=True, help_text='Department or division', max_length=100, verbose_name='department')),
                ('hire_date', models.DateField(blank=True, help_text='Date of hiring/association', null=True, verbose_name='hire date')),
                ('termination_date', models.DateField(blank=True, help_text='Date of termination/separation', null=True, verbose_name='termination date')),
                ('email', models.EmailField(blank=True, help_text='Professional email address for notifications', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, help_text='Mobile phone number', max_length=50, verbose_name='mobile')),
                ('address', models.TextField(blank=True, help_text='Home address', verbose_name='address')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('company', models.ForeignKey(blank=True, help_text='Company this person is associated with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_persons', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager/supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='parties.associatedperson', verbose_name='manager')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.OneToOneField(blank=True, help_text='Linked platform user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_person', to=settings.AUTH_USER_MODEL, verbose_name='user account')),
                ('person_type', models.ForeignKey(help_text='Classification of this person', on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='parties.associatedpersontype', verbose_name='person type')),
            ],
            options={
                'verbose_name': 'associated person',
                'verbose_name_plural': 'associated persons',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('name', models.CharField(help_text='Client name', max_length=255, verbose_name='name')),
                ('trade_name', models.CharField(blank=True, help_text='Commercial/trade name (DBA)', max_length=255, verbose_name='trade name')),
                ('registration_number', models.CharField(blank=True, help_text='Official registration number', max_length=100, null=True, unique=True, verbose_name='registration number')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100, null=True, unique=True, verbose_name='tax ID')),
                ('vat_number', models.CharField(blank=True, help_text='Value Added Tax number', max_length=100, null=True, unique=True, verbose_name='VAT number')),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=50, verbose_name='phone')),
                ('address', models.TextField(blank=True, help_text='Physical address', verbose_name='address')),
                ('website', models.URLField(blank=True, help_text='Website URL', verbose_name='website')),
                ('credit_limit', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Maximum credit allowed', max_digits=18, verbose_name='credit limit')),
                ('payment_terms', models.CharField(blank=True, help_text='Default payment terms (e.g., Net 30)', max_length=100, verbose_name='payment terms')),
                ('default_currency', models.CharField(default='MAD', help_text='ISO 4217 currency code', max_length=3, verbose_name='default currency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('company', models.ForeignKey(blank=True, help_text='Company this client belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('default_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuration.paymentmethod', verbose_name='default payment method')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('name', models.CharField(help_text='Party name', max_length=255, verbose_name='name')),
                ('trade_name', models.CharField(blank=True, help_text='Commercial/trade name', max_length=255, verbose_name='trade name')),
                ('party_category', models.CharField(blank=True, help_text="Category for grouping (e.g., 'Freelancer', 'Government Agency')", max_length=100, verbose_name='party category')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100, verbose_name='tax ID')),
                ('vat_number', models.CharField(blank=True, help_text='Value Added Tax number', max_length=100, verbose_name='VAT number')),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Contact phone', max_length=50, verbose_name='phone')),
                ('address', models.TextField(blank=True, help_text='Physical address', verbose_name='address')),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this party is used frequently', verbose_name='recurring')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'external party',
                'verbose_name_plural': 'external parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('name', models.CharField(help_text='Supplier name', max_length=255, verbose_name='name')),
                ('trade_name', models.CharField(blank=True, help_text='Commercial/trade name', max_length=255, verbose_name='trade name')),
                ('registration_number', models.CharField(blank=True, help_text='Official registration number', max_length=100, null=True, unique=True, verbose_name='registration number')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100, null=True, unique=True, verbose_name='tax ID')),
                ('vat_number', models.CharField(blank=True, help_text='Value Added Tax number', max_length=100, null=True, unique=True, verbose_name='VAT number')),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=50, verbose_name='phone')),
                ('address', models.TextField(blank=True, help_text='Physical address', verbose_name='address')),
                ('website', models.URLField(blank=True, help_text='Website URL', verbose_name='website')),
                ('payment_terms', models.CharField(blank=True, help_text='Default payment terms (e.g., Net 30)', max_length=100, verbose_name='payment terms')),
                ('default_currency', models.CharField(default='MAD', help_text='ISO 4217 currency code', max_length=3, verbose_name='default currency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', max_length=20, verbose_name='status')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('company', models.ForeignKey(blank=True, help_text='Company this supplier belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('default_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuration.paymentmethod', verbose_name='default payment method')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='associatedpersontype',
            index=models.Index(fields=['name'], name='ap_type_name_idx'),
        ),
        migrations.AddIndex(
            model_name='associatedpersontype',
            index=models.Index(fields=['status'], name='ap_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='associatedperson',
            index=models.Index(fields=['last_name', 'first_name'], name='ap_name_idx'),
        ),
        migrations.AddIndex(
            model_name='associatedperson',
            index=models.Index(fields=['status'], name='ap_status_idx'),
        ),
        migrations.AddIndex(
            model_name='associatedperson',
            index=models.Index(fields=['national_id'], name='ap_national_id_idx'),
        ),
        migrations.AddIndex(
            model_name='associatedperson',
            index=models.Index(fields=['email'], name='ap_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='associatedperson',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_associated_person_reference'),
        ),
        migrations.AddConstraint(
            model_name='associatedperson',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id__gt', '')), fields=('national_id',), name='unique_ap_national_id'),
        ),
        migrations.AddConstraint(
            model_name='associatedperson',
            constraint=models.UniqueConstraint(condition=models.Q(('passport_number__gt', '')), fields=('passport_number',), name='unique_ap_passport_number'),
        ),
        migrations.AddConstraint(
            model_name='associatedperson',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id__gt', '')), fields=('employee_id',), name='unique_ap_employee_id'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='client_name_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['status'], name='client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['tax_id'], name='client_tax_id_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['vat_number'], name='client_vat_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_client_reference'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id__gt', '')), fields=('tax_id',), name='unique_client_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('vat_number__gt', '')), fields=('vat_number',), name='unique_client_vat_number'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number__gt', '')), fields=('registration_number',), name='unique_client_reg_number'),
        ),
        migrations.AddIndex(
            model_name='externalparty',
            index=models.Index(fields=['name'], name='ext_party_name_idx'),
        ),
        migrations.AddIndex(
            model_name='externalparty',
            index=models.Index(fields=['party_category'], name='ext_party_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='externalparty',
            index=models.Index(fields=['is_recurring'], name='ext_party_recurring_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalparty',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_external_party_reference'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='supplier_name_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['status'], name='supplier_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tax_id'], name='supplier_tax_id_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['vat_number'], name='supplier_vat_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_supplier_reference'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id__gt', '')), fields=('tax_id',), name='unique_supplier_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('vat_number__gt', '')), fields=('vat_number',), name='unique_supplier_vat_number'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number__gt', '')), fields=('registration_number',), name='unique_supplier_reg_number'),
        ),
    ]
