# Generated by Django 6.0 on 2026-08-06 09:23

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_custom_fields'),
        ('configuration', '0001_initial'),
        ('financial_records', '0002_financialrecord_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Administrator-defined attributes for this record.', verbose_name='custom fields')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('kind', models.CharField(choices=[('bank', 'Bank account'), ('cash', 'Cash box'), ('wallet', 'Mobile wallet'), ('other', 'Other')], default='bank', max_length=20, verbose_name='kind')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('bank_name', models.CharField(blank=True, max_length=150, verbose_name='bank name')),
                ('account_number', models.CharField(blank=True, max_length=64, verbose_name='account number')),
                ('iban', models.CharField(blank=True, max_length=64, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=20, verbose_name='SWIFT/BIC')),
                ('opening_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Balance at the moment the account was brought onto the platform.', max_digits=18, verbose_name='opening balance')),
                ('current_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Maintained by the treasury services. Never write this directly; use post_transaction so the ledger and the balance stay in step.', max_digits=18, verbose_name='current balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_accounts', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['company', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('statement_balance', models.DecimalField(decimal_places=4, help_text='Closing balance printed on the bank statement.', max_digits=18, verbose_name='statement balance')),
                ('computed_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Ledger balance at period end, recorded when completed.', max_digits=18, verbose_name='computed balance')),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20, verbose_name='status')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='treasury.account', verbose_name='account')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='completed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'reconciliation',
                'verbose_name_plural': 'reconciliations',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Administrator-defined attributes for this record.', verbose_name='custom fields')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=20, verbose_name='direction')),
                ('amount', models.DecimalField(decimal_places=4, help_text='Always positive. The direction field carries the sign.', max_digits=18, verbose_name='amount')),
                ('currency', models.CharField(default='MAD', max_length=3, verbose_name='currency')),
                ('transaction_date', models.DateField(verbose_name='transaction date')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('external_reference', models.CharField(blank=True, help_text='Cheque number, wire reference, receipt number.', max_length=120, verbose_name='external reference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('transfer_group', models.UUIDField(blank=True, db_index=True, help_text='Shared by the two legs of an internal transfer.', null=True, verbose_name='transfer group')),
                ('is_reconciled', models.BooleanField(default=False, verbose_name='reconciled')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='treasury.account', verbose_name='account')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('financial_record', models.ForeignKey(blank=True, help_text='The invoice or expense this payment settles, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to='financial_records.financialrecord', verbose_name='financial record')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_transactions', to='configuration.paymentmethod', verbose_name='payment method')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_transactions', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='treasury.reconciliation', verbose_name='reconciliation')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasury_transactions', to='configuration.transactiontype', verbose_name='transaction type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['company', 'is_active'], name='trs_acc_company_active_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['kind'], name='trs_acc_kind_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('company', 'name'), name='trs_acc_unique_name_per_company'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['account', 'status'], name='trs_rec_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliation',
            index=models.Index(fields=['period_end'], name='trs_rec_period_end_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliation',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='trs_rec_period_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'status'], name='trs_txn_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='trs_txn_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'is_archived'], name='trs_txn_status_arch_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_reconciled'], name='trs_txn_reconciled_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='trs_txn_amount_strictly_positive'),
        ),
    ]
