# Generated by Django 6.0

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_complementary_fields"),
        ("treasury", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="amount"
                    ),
                ),
                (
                    "filled_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="filled at"),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="note"),
                ),
                (
                    "is_carried_over",
                    models.BooleanField(
                        default=False,
                        help_text="True when this day's amount was copied from a previous day.",
                        verbose_name="carried over",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_budgets",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "filled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_budgets_filled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="filled by",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily budget",
                "verbose_name_plural": "daily budgets",
                "ordering": ["-date", "company__name"],
            },
        ),
        migrations.AddIndex(
            model_name="dailybudget",
            index=models.Index(
                fields=["company", "date"], name="daily_budget_co_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailybudget",
            index=models.Index(fields=["date"], name="daily_budget_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="dailybudget",
            constraint=models.UniqueConstraint(
                fields=("company", "date"),
                name="unique_daily_budget_per_company_date",
            ),
        ),
    ]
