# Generated by Django 6.0 on 2026-08-27 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deadlines", "0002_deadline_recurrence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeadlineOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="1-based position of this period in the deadline's history."
                    ),
                ),
                ("due_at", models.DateTimeField(db_index=True)),
                (
                    "period_label",
                    models.CharField(
                        blank=True,
                        help_text='Human period key, e.g. "2026-08" monthly or "2026-Q3" quarterly.',
                        max_length=40,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deadline_occurrences_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deadline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="deadlines.deadline",
                    ),
                ),
            ],
            options={
                "ordering": ["-due_at"],
                "indexes": [
                    models.Index(fields=["deadline", "-due_at"], name="deadline_occ_recent_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("deadline", "due_at"), name="deadline_occurrence_unique_period"
                    )
                ],
            },
        ),
    ]
