# Generated by Django 6.0 on 2026-07-15 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('email', models.EmailField(db_index=True, help_text='Email address used in login attempt', max_length=254, verbose_name='email')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address of the login attempt', verbose_name='IP address')),
                ('attempt_count', models.PositiveIntegerField(default=1, help_text='Number of consecutive failed attempts', verbose_name='attempt count')),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp until which the account/IP is locked', null=True, verbose_name='locked until')),
                ('lockout_count', models.PositiveIntegerField(default=0, help_text='Number of times this email/IP has been locked', verbose_name='lockout count')),
                ('user_agent', models.TextField(blank=True, help_text='Full user agent string', verbose_name='user agent')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for login failure', max_length=255, verbose_name='failure reason')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether this email/IP is currently locked', verbose_name='is locked')),
                ('last_attempt_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last failed attempt', verbose_name='last attempt at')),
                ('first_attempt_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of first failed attempt in current series', verbose_name='first attempt at')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
            ],
            options={
                'verbose_name': 'failed login attempt',
                'verbose_name_plural': 'failed login attempts',
                'ordering': ['-last_attempt_at'],
                'indexes': [models.Index(fields=['email', 'is_archived'], name='fla_email_arch_idx'), models.Index(fields=['ip_address', 'is_archived'], name='fla_ip_arch_idx'), models.Index(fields=['locked_until', 'is_archived'], name='fla_locked_arch_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('email', 'ip_address'), name='unique_active_failed_login_per_email_ip')],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('token', models.CharField(db_index=True, help_text='Opaque refresh token string', max_length=512, unique=True, verbose_name='token')),
                ('token_family', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Groups related access/refresh tokens for a session', verbose_name='token family')),
                ('access_token_jti', models.CharField(blank=True, help_text='JTI of the access token this refresh token created', max_length=256, verbose_name='access token JTI')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this refresh token expires', verbose_name='expires at')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this token was revoked', null=True, verbose_name='revoked at')),
                ('revoked_reason', models.CharField(blank=True, help_text='Reason for token revocation', max_length=255, verbose_name='revocation reason')),
                ('user_agent', models.TextField(blank=True, help_text='User agent at token creation', verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address at token creation', null=True, verbose_name='IP address')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('replaced_by', models.ForeignKey(blank=True, help_text='Token that replaced this one during rotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_tokens', to='authentication.refreshtoken', verbose_name='replaced by')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked this token', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(help_text='User who owns this refresh token', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'refresh token',
                'verbose_name_plural': 'refresh tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_archived'], name='rt_user_archived_idx'), models.Index(fields=['token'], name='rt_token_idx'), models.Index(fields=['expires_at', 'is_archived'], name='rt_exp_arch_idx'), models.Index(fields=['token_family'], name='rt_family_idx'), models.Index(fields=['revoked_at', 'is_archived'], name='rt_revoked_arch_idx')],
                'constraints': [models.UniqueConstraint(fields=('token',), name='unique_refresh_token')],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('session_key', models.CharField(db_index=True, help_text='Opaque session identifier', max_length=255, unique=True, verbose_name='session key')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True, verbose_name='IP address')),
                ('device_fingerprint', models.CharField(blank=True, help_text='Device/browser fingerprint hash', max_length=256, verbose_name='device fingerprint')),
                ('device_name', models.CharField(blank=True, help_text='Human-readable device name', max_length=255, verbose_name='device name')),
                ('device_type', models.CharField(blank=True, help_text='Device type: desktop, mobile, tablet, etc.', max_length=50, verbose_name='device type')),
                ('browser', models.CharField(blank=True, help_text='Browser name and version', max_length=100, verbose_name='browser')),
                ('operating_system', models.CharField(blank=True, help_text='Operating system', max_length=100, verbose_name='operating system')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('is_current', models.BooleanField(default=False, help_text='Whether this is the current active session', verbose_name='current session')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the session is currently active', verbose_name='active')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last activity timestamp', verbose_name='last activity')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this session expires', verbose_name='expires at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('revoked_reason', models.CharField(blank=True, max_length=255, verbose_name='revocation reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL, verbose_name='revoked by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_archived'], name='us_user_archived_idx'), models.Index(fields=['session_key'], name='us_session_key_idx'), models.Index(fields=['user', 'is_active', 'is_archived'], name='us_user_active_arch_idx'), models.Index(fields=['expires_at', 'is_archived'], name='us_exp_arch_idx'), models.Index(fields=['device_fingerprint'], name='us_fingerprint_idx')],
                'constraints': [models.UniqueConstraint(fields=('session_key',), name='unique_user_session_key')],
            },
        ),
    ]
