# Generated by Django 6.0 on 2026-07-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedloginattempt',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent of the login attempt', verbose_name='user agent'),
        ),
    ]
