# Generated by Django 6.0 on 2026-08-05 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_failedloginattempt_user_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='failedloginattempt',
            index=models.Index(fields=['email', 'ip_address'], name='fla_email_ip_idx'),
        ),
    ]
