import uuid
from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
 dependencies=[("contenttypes","0002_remove_content_type_name"),("companies","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name="Notification",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("category",models.CharField(choices=[("mention","Mention"),("payroll","Payroll"),("cnss","CNSS"),("document","Financial document"),("report","Report"),("payment","Payment"),("system","System")],db_index=True,max_length=32)),("title",models.CharField(max_length=160)),("message",models.CharField(blank=True,max_length=500)),("destination",models.CharField(blank=True,max_length=500)),("metadata",models.JSONField(blank=True,default=dict)),("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),("read_at",models.DateTimeField(blank=True,db_index=True,null=True)),("actor",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="notifications_created",to=settings.AUTH_USER_MODEL)),("company",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="notifications",to="companies.company")),("recipient",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="notifications",to=settings.AUTH_USER_MODEL))],options={"ordering":["-created_at"],"indexes":[models.Index(fields=["recipient","read_at","-created_at"],name="collab_notif_inbox_idx")]}),
  migrations.CreateModel(name="Mention",fields=[("id",models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),("object_id",models.UUIDField(db_index=True)),("target_label",models.CharField(max_length=240)),("destination",models.CharField(max_length=500)),("message",models.CharField(blank=True,max_length=500)),("created_at",models.DateTimeField(auto_now_add=True,db_index=True)),("read_at",models.DateTimeField(blank=True,null=True)),("resolved_at",models.DateTimeField(blank=True,db_index=True,null=True)),("company",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="mentions",to="companies.company")),("content_type",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="contenttypes.contenttype")),("tagged_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="mentions_created",to=settings.AUTH_USER_MODEL)),("tagged_user",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="mentions_received",to=settings.AUTH_USER_MODEL))],options={"ordering":["-created_at"],"indexes":[models.Index(fields=["tagged_user","resolved_at","-created_at"],name="collab_mention_queue_idx"),models.Index(fields=["content_type","object_id"],name="collab_mention_target_idx")],"constraints":[models.UniqueConstraint(condition=models.Q(("resolved_at__isnull",True)),fields=("tagged_user","content_type","object_id"),name="collab_unique_active_mention")]}),
 ]
