# Generated by Django 6.0 on 2026-07-19 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cnssdeclaration',
            name='unique_active_cnss_per_person_company',
        ),
        migrations.AddConstraint(
            model_name='cnssdeclaration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('is_currently_declared', True)), fields=('person', 'company'), name='unique_active_cnss_declared_per_person_company'),
        ),
    ]
