# Generated by Django 6.0 on 2026-08-06 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_remove_cnssdeclaration_unique_active_cnss_per_person_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollpayment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='cancelled at'),
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by'),
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='status',
            field=models.CharField(choices=[('recorded', 'Recorded'), ('cancelled', 'Cancelled')], default='recorded', help_text='Cycle 18 decision C-4: a cancelled payment stays in the record for audit purposes.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='cnssmonthlydeclaration',
            name='cnss_declaration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_declarations', to='personnel.cnssdeclaration', verbose_name='CNSS declaration'),
        ),
        migrations.AlterField(
            model_name='employmentsalary',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='personnel.employment', verbose_name='employment'),
        ),
        migrations.AlterField(
            model_name='monthlypayrollrecord',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_records', to='personnel.employment', verbose_name='employment'),
        ),
        migrations.AlterField(
            model_name='payrolladjustment',
            name='payroll_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='personnel.monthlypayrollrecord', verbose_name='payroll record'),
        ),
        migrations.AlterField(
            model_name='payrollpayment',
            name='payroll_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='personnel.monthlypayrollrecord', verbose_name='payroll record'),
        ),
    ]
