# Generated by Django 6.0 on 2026-08-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0005_personnel_person_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="absence_day_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Amount deducted per unpaid absence day for this employee. Leave empty to deduct at the worked-day rate.",
                max_digits=18,
                null=True,
                verbose_name="absence-day rate",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="worked_day_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Amount earned per worked day for this employee. Leave empty to derive it from gross salary / scheduled working days.",
                max_digits=18,
                null=True,
                verbose_name="worked-day rate",
            ),
        ),
    ]
