# Generated by Django 6.0 on 2026-09-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0006_employment_day_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="employment_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("on_leave", "On Leave"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                    ("cnss_only", "CNSS Only"),
                    ("resigned", "Resigned"),
                    ("retired", "Retired"),
                    ("former", "Former"),
                    ("other", "Other"),
                ],
                default="active",
                help_text="Current employment status",
                max_length=20,
                verbose_name="employment status",
            ),
        ),
        migrations.AlterField(
            model_name="personnelperson",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("suspended", "Suspended"),
                    ("terminated", "Terminated"),
                    ("archived", "Archived"),
                ],
                default="active",
                help_text="Current status",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
