# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_complementary_fields"),
        ("personnel", "0007_alter_employment_employment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty to connect this employment to the whole group.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employments",
                to="companies.company",
                verbose_name="company",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="payout_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Espèces"), ("bank", "Virement bancaire")],
                default="cash",
                help_text="Espèces or bank transfer. Independent of the PaymentMethod catalog.",
                max_length=16,
                verbose_name="payout method",
            ),
        ),
    ]
