# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


def backfill_person_company(apps, schema_editor):
    PersonnelPerson = apps.get_model("personnel", "PersonnelPerson")
    Employment = apps.get_model("personnel", "Employment")
    for person in PersonnelPerson.objects.all().iterator():
        emp = (
            Employment.objects.filter(
                person_id=person.pk,
                is_active=True,
                is_archived=False,
            )
            .exclude(company_id=None)
            .order_by("pk")
            .first()
        )
        if emp and emp.company_id:
            person.company_id = emp.company_id
            person.save(update_fields=["company_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0005_company_complementary_fields"),
        ("personnel", "0008_employment_group_and_payout"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnelperson",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave empty to connect this person to the whole group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="personnel_people",
                to="companies.company",
                verbose_name="company",
            ),
        ),
        migrations.RunPython(backfill_person_company, migrations.RunPython.noop),
    ]
