# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnel", "0009_personnelperson_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="authorized_leave_days_per_year",
            field=models.PositiveIntegerField(
                default=18,
                help_text="Paid leave days granted on this employment each calendar year.",
                verbose_name="authorized leave days per year",
            ),
        ),
    ]
