# Generated by Django 6.0 on 2026-07-15 10:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('name', models.CharField(help_text='Legal name of the company', max_length=255, verbose_name='name')),
                ('trade_name', models.CharField(blank=True, help_text='Commercial/trade name (DBA)', max_length=255, verbose_name='trade name')),
                ('registration_number', models.CharField(blank=True, help_text='Official company registration number', max_length=100, null=True, unique=True, verbose_name='registration number')),
                ('tax_id', models.CharField(blank=True, help_text='Tax identification number', max_length=100, null=True, unique=True, verbose_name='tax ID')),
                ('vat_number', models.CharField(blank=True, help_text='Value Added Tax number', max_length=100, null=True, unique=True, verbose_name='VAT number')),
                ('email', models.EmailField(blank=True, help_text='Primary contact email', max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, help_text='Primary contact phone', max_length=50, verbose_name='phone')),
                ('address', models.TextField(blank=True, help_text='Physical address', verbose_name='address')),
                ('website', models.URLField(blank=True, help_text='Company website', verbose_name='website')),
                ('default_currency', models.CharField(default='MAD', help_text='ISO 4217 currency code', max_length=3, verbose_name='default currency')),
                ('default_language', models.CharField(default='fr', help_text='ISO 639-1 language code', max_length=2, verbose_name='default language')),
                ('timezone', models.CharField(default='Africa/Casablanca', help_text='IANA timezone identifier', max_length=50, verbose_name='timezone')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='active', help_text='Current operational status', max_length=20, verbose_name='status')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('key', models.CharField(help_text='Unique preference key (alphanumeric, underscore, hyphen)', max_length=100, verbose_name='key')),
                ('value', models.TextField(help_text='Stored as string, cast by preference_type', verbose_name='value')),
                ('preference_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', help_text='Data type for value casting', max_length=20, verbose_name='type')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of this preference', verbose_name='description')),
                ('is_system', models.BooleanField(default=False, help_text='System preferences cannot be deleted by users', verbose_name='system preference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_preferences_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_preferences_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'company preference',
                'verbose_name_plural': 'company preferences',
                'ordering': ['company', 'key'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_record_type', models.CharField(blank=True, help_text='Default financial record type for new records', max_length=100, verbose_name='default record type')),
                ('auto_validate_records', models.BooleanField(default=False, help_text='Automatically validate records on creation', verbose_name='auto-validate records')),
                ('auto_approve_records', models.BooleanField(default=False, help_text='Automatically approve records on validation', verbose_name='auto-approve records')),
                ('require_payment_confirmation', models.BooleanField(default=True, help_text='Require explicit confirmation for payments', verbose_name='require payment confirmation')),
                ('allow_internal_transfers', models.BooleanField(default=True, help_text='Allow transfers between company accounts', verbose_name='allow internal transfers')),
                ('require_transfer_approval', models.BooleanField(default=True, help_text='Require approval for internal transfers', verbose_name='require transfer approval')),
                ('record_reference_prefix', models.CharField(blank=True, help_text="Prefix for financial record references (e.g., 'INV-')", max_length=20, verbose_name='record reference prefix')),
                ('transaction_reference_prefix', models.CharField(blank=True, help_text="Prefix for treasury transaction references (e.g., 'TRX-')", max_length=20, verbose_name='transaction reference prefix')),
                ('notify_on_payment', models.BooleanField(default=True, help_text='Send notifications when payments are recorded', verbose_name='notify on payment')),
                ('notify_on_transfer', models.BooleanField(default=True, help_text='Send notifications when transfers complete', verbose_name='notify on transfer')),
                ('notify_on_report_generated', models.BooleanField(default=True, help_text='Send notifications when reports are generated', verbose_name='notify on report generated')),
                ('assistants_can_manage_records', models.BooleanField(default=True, help_text='Allow assistants to create/edit records', verbose_name='assistants can manage records')),
                ('assistants_can_manage_parties', models.BooleanField(default=True, help_text='Allow assistants to create/edit clients/suppliers', verbose_name='assistants can manage parties')),
                ('assistants_can_create_transfers', models.BooleanField(default=False, help_text='Allow assistants to create internal transfers', verbose_name='assistants can create transfers')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('default_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configuration.paymentmethod', verbose_name='default payment method')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_settings_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'company settings',
                'verbose_name_plural': 'company settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['reference'], name='company_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['status'], name='company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tax_id'], name='company_tax_id_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['registration_number'], name='company_reg_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_archived', 'status'], name='company_archive_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_company_reference'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id__gt', '')), fields=('tax_id',), name='unique_company_tax_id'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('vat_number__gt', '')), fields=('vat_number',), name='unique_company_vat_number'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('registration_number__gt', '')), fields=('registration_number',), name='unique_company_reg_number'),
        ),
        migrations.AddIndex(
            model_name='companypreference',
            index=models.Index(fields=['company', 'key'], name='pref_company_key_idx'),
        ),
        migrations.AddConstraint(
            model_name='companypreference',
            constraint=models.UniqueConstraint(fields=('company', 'key'), name='unique_company_preference_key'),
        ),
    ]
