# Generated by Django 6.0 on 2026-08-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='observations',
            field=models.TextField(blank=True, help_text='Internal notes and archive history', verbose_name='observations'),
        ),
    ]
