# Generated by Django 6.0 on 2026-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Amount threshold requiring approval', max_digits=18, null=True, verbose_name='approval threshold'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='auto_send_invoices',
            field=models.BooleanField(default=False, help_text='Automatically send invoices upon creation', verbose_name='auto send invoices'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='default_currency',
            field=models.CharField(default='MAD', help_text='Default currency for invoices', max_length=3, verbose_name='default currency'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='default_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default tax rate percentage', max_digits=5, null=True, verbose_name='default tax rate'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='invoice_footer_text',
            field=models.TextField(blank=True, help_text='Footer text for invoices', verbose_name='invoice footer text'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='require_approval',
            field=models.BooleanField(default=False, help_text='Require approval for financial records', verbose_name='require approval'),
        ),
    ]
