# Generated by Django 6.0 on 2026-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companysettings_approval_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Administrator-defined attributes for this record.', verbose_name='custom fields'),
        ),
    ]
