# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_custom_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="Identifiant Commun de l'Entreprise (ICE)",
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Identifiant Commun de l'Entreprise",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="cnss_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Company CNSS affiliation number",
                max_length=100,
                verbose_name="Numéro CNSS",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="patent_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Patent / patente number",
                max_length=100,
                verbose_name="Patente",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="rib",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Company bank RIB",
                max_length=64,
                verbose_name="RIB",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="activities",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Business activities",
                verbose_name="Activités",
            ),
        ),
    ]
