# Generated by Django 6.0 on 2026-09-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_tickets", "0002_clientticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="helpticket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
