# Generated by Django 6.0 on 2026-09-05 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_custom_fields"),
        ("leaves", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leaves",
                to="companies.company",
            ),
        ),
        migrations.AddField(
            model_name="leave",
            name="decision_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leave",
            name="decision_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="leave",
            name="leave_type_other",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "Congé annuel"),
                    ("exceptional", "Congé exceptionnel"),
                    ("other", "Autre"),
                    ("sick", "Sick Leave"),
                    ("maternity", "Maternity Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                max_length=50,
            ),
        ),
    ]
