# Generated by Django 6.0 on 2026-08-07 12:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_company_custom_fields'),
        ('configuration', '0001_initial'),
        ('financial_records', '0002_financialrecord_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='Administrator-defined attributes for this record.', verbose_name='custom fields')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('period_label', models.CharField(help_text="Human-readable period, e.g. '2026-07' or 'FY2026'", max_length=50, verbose_name='period label')),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('current_official', 'Current Official'), ('outdated', 'Outdated')], default='preview', max_length=20, verbose_name='status')),
                ('latest_version_number', models.PositiveIntegerField(default=0, help_text='Denormalised counter so the next version number never requires a COUNT() race.', verbose_name='latest version number')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to='configuration.reporttype', verbose_name='report type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'generated report',
                'verbose_name_plural': 'generated reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('version_number', models.PositiveIntegerField(verbose_name='version number')),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('current_official', 'Current Official'), ('outdated', 'Outdated')], default='preview', max_length=20, verbose_name='status')),
                ('generation_mode', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('preview', 'Preview')], default='manual', max_length=20, verbose_name='generation mode')),
                ('calculation_mode', models.CharField(choices=[('keep_missing', 'Keep missing values'), ('treat_missing_as_zero', 'Treat missing periods as zero')], default='keep_missing', help_text='How this version handled an incomplete reporting period (blueprint Section 6).', max_length=30, verbose_name='calculation mode')),
                ('is_partial', models.BooleanField(default=False, help_text='True when the reporting period was incomplete at generation time.', verbose_name='is partial')),
                ('missing_periods', models.JSONField(blank=True, default=list, help_text='Sub-periods marked Waiting/Pending/N-A because no data existed yet.', verbose_name='missing periods')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Full computed report snapshot as generated, independent of ReportValue rows.', verbose_name='payload')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='generated at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('regeneration_reason', models.TextField(blank=True, help_text='Required when this version supersedes a prior one for the same report.', verbose_name='regeneration reason')),
                ('outdated_at', models.DateTimeField(blank=True, null=True, verbose_name='outdated at')),
                ('outdated_reason', models.TextField(blank=True, verbose_name='outdated reason')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='reports.generatedreport', verbose_name='report')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_report_versions', to=settings.AUTH_USER_MODEL, verbose_name='reviewed by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'report version',
                'verbose_name_plural': 'report versions',
                'ordering': ['report', '-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ReportValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('key', models.CharField(help_text="Stable machine key, e.g. 'fuel_expense.2026.01'.", max_length=100, verbose_name='key')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='amount')),
                ('period_label', models.CharField(blank=True, max_length=50, verbose_name='period label')),
                ('is_available', models.BooleanField(default=True, help_text='False for Waiting/Pending/N-A values from an incomplete period (blueprint Section 6).', verbose_name='is available')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reports.reportvalue', verbose_name='parent value')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.reportversion', verbose_name='version')),
            ],
            options={
                'verbose_name': 'report value',
                'verbose_name_plural': 'report values',
                'ordering': ['version', 'key'],
            },
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='current_version',
            field=models.ForeignKey(blank=True, help_text='The latest version generated for this report, regardless of approval status.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.reportversion', verbose_name='current version'),
        ),
        migrations.CreateModel(
            name='ReportValueSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('contribution_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text="This record's own contribution to the parent ReportValue's amount.", max_digits=18, verbose_name='contribution amount')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('financial_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_value_sources', to='financial_records.financialrecord', verbose_name='financial record')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='reports.reportvalue', verbose_name='value')),
            ],
            options={
                'verbose_name': 'report value source',
                'verbose_name_plural': 'report value sources',
                'ordering': ['value', 'financial_record'],
                'constraints': [models.UniqueConstraint(fields=('value', 'financial_record'), name='unique_report_value_source')],
            },
        ),
        migrations.AddIndex(
            model_name='reportversion',
            index=models.Index(fields=['report', 'status'], name='rv_report_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportversion',
            constraint=models.UniqueConstraint(fields=('report', 'version_number'), name='unique_report_version_number'),
        ),
        migrations.AddIndex(
            model_name='reportvalue',
            index=models.Index(fields=['version', 'key'], name='rval_version_key_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['company', 'report_type', 'period_start'], name='gr_company_type_period_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status'], name='gr_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.UniqueConstraint(fields=('reference',), name='unique_generated_report_reference'),
        ),
        migrations.AddConstraint(
            model_name='generatedreport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('status', 'current_official')), fields=('company', 'report_type', 'period_start', 'period_end'), name='unique_current_official_report_per_period'),
        ),
    ]
