# Generated by Django 6.0 on 2026-08-07 12:27

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportversion',
            name='payload',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Full computed report snapshot as generated, independent of ReportValue rows. Uses DjangoJSONEncoder because generated values are Decimal, which the default JSON encoder cannot serialize.', verbose_name='payload'),
        ),
    ]
