# Generated by Django 6.0 on 2026-08-06 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('entity', models.CharField(db_index=True, help_text='Which entity this attribute belongs to, e.g. companies.Company', max_length=100, verbose_name='entity')),
                ('key', models.CharField(help_text='Machine name used in the API payload, e.g. domains', max_length=60, verbose_name='key')),
                ('label', models.CharField(help_text='Human readable label shown in the interface', max_length=120, verbose_name='label')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('data_type', models.CharField(choices=[('string', 'Text (single line)'), ('text', 'Text (multi line)'), ('integer', 'Whole number'), ('decimal', 'Decimal number'), ('boolean', 'Yes / No'), ('date', 'Date'), ('choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('email', 'Email address'), ('url', 'URL')], default='string', max_length=20, verbose_name='data type')),
                ('is_required', models.BooleanField(default=False, verbose_name='required')),
                ('default_value', models.TextField(blank=True, help_text='Applied when the attribute is absent. Stored as text.', verbose_name='default value')),
                ('choices', models.JSONField(blank=True, default=list, help_text='Allowed values for choice and multi_choice types', verbose_name='choices')),
                ('max_length', models.PositiveIntegerField(blank=True, help_text='Optional length limit for text attributes', null=True, verbose_name='maximum length')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Deactivate instead of deleting. Existing stored values are kept so turning an attribute back on does not lose data.', verbose_name='active')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'custom field definition',
                'verbose_name_plural': 'custom field definitions',
                'ordering': ['entity', 'display_order', 'key'],
                'indexes': [models.Index(fields=['entity', 'is_active'], name='cfd_entity_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity', 'key'), name='cfd_unique_key_per_entity')],
            },
        ),
        migrations.CreateModel(
            name='TemplateImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('bundle_name', models.CharField(max_length=200, verbose_name='bundle name')),
                ('bundle_version', models.CharField(blank=True, max_length=50, verbose_name='bundle version')),
                ('source', models.CharField(blank=True, help_text='File name or upload origin', max_length=200, verbose_name='source')),
                ('outcome', models.CharField(choices=[('applied', 'Applied'), ('dry_run', 'Dry run'), ('failed', 'Failed')], default='applied', max_length=20, verbose_name='outcome')),
                ('created_count', models.PositiveIntegerField(default=0, verbose_name='created')),
                ('updated_count', models.PositiveIntegerField(default=0, verbose_name='updated')),
                ('skipped_count', models.PositiveIntegerField(default=0, verbose_name='skipped')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Per-template outcome and any errors', verbose_name='details')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'template import log',
                'verbose_name_plural': 'template import logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bundle_name'], name='til_bundle_idx')],
            },
        ),
    ]
