# Generated by Django 6.0 on 2026-08-06 07:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_companysettings_approval_threshold_and_more'),
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Reference')),
                ('record_date', models.DateField(help_text='Date the document itself bears, not the date it was keyed in.', verbose_name='record date')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('currency', models.CharField(default='MAD', help_text='ISO 4217 code. Mixed-currency records are not supported.', max_length=3, verbose_name='currency')),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Sum of the debit side. Derived from the lines.', max_digits=18, verbose_name='total amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='posted at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='cancellation reason')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_records', to='configuration.category', verbose_name='category')),
                ('company', models.ForeignKey(help_text='Company the record belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='companies.company', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_financial_records', to=settings.AUTH_USER_MODEL, verbose_name='posted by')),
                ('record_type', models.ForeignKey(help_text='Business type, e.g. Purchase Invoice or Fuel Expense.', on_delete=django.db.models.deletion.PROTECT, related_name='financial_records', to='configuration.financialrecordtype', verbose_name='record type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'financial record',
                'verbose_name_plural': 'financial records',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('file_key', models.CharField(help_text='Object storage key. Not a URL, so the bucket can move.', max_length=512, verbose_name='file key')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='content type')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='size in bytes')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='financial_records.financialrecord', verbose_name='record')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialRecordLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived at')),
                ('line_number', models.PositiveIntegerField(help_text='Ordering within the record, 1-based.', verbose_name='line number')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('debit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='debit')),
                ('credit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18, verbose_name='credit')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_archived_by', to=settings.AUTH_USER_MODEL, verbose_name='Archived by')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_record_lines', to='configuration.category', verbose_name='category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='financial_records.financialrecord', verbose_name='record')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'financial record line',
                'verbose_name_plural': 'financial record lines',
                'ordering': ['record', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['company', 'status'], name='fr_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['record_date'], name='fr_record_date_idx'),
        ),
        migrations.AddIndex(
            model_name='financialrecord',
            index=models.Index(fields=['status', 'is_archived'], name='fr_status_arch_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialrecord',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='fr_total_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['record'], name='fra_record_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.UniqueConstraint(fields=('record', 'file_key'), name='fra_unique_file_per_record'),
        ),
        migrations.AddIndex(
            model_name='financialrecordline',
            index=models.Index(fields=['record', 'line_number'], name='frl_record_line_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialrecordline',
            constraint=models.UniqueConstraint(fields=('record', 'line_number'), name='frl_unique_line_number_per_record'),
        ),
        migrations.AddConstraint(
            model_name='financialrecordline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='frl_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='financialrecordline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='frl_exactly_one_side'),
        ),
    ]
