# Generated by Django 6.0 on 2026-08-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='Administrator-defined attributes for this record.', verbose_name='custom fields'),
        ),
    ]
