import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [("financial_records", "0003_financialrecord_client_supplier"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="FinancialDocumentTemplate", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")), ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")), ("is_archived", models.BooleanField(default=False, verbose_name="Archived")), ("archived_at", models.DateTimeField(blank=True, null=True, verbose_name="Archived at")),
            ("name", models.CharField(max_length=200, verbose_name="name")), ("version", models.PositiveIntegerField(verbose_name="version")), ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")], default="draft", max_length=20, verbose_name="status")), ("description", models.TextField(blank=True, verbose_name="description")), ("effective_from", models.DateField(blank=True, null=True, verbose_name="effective from")), ("effective_to", models.DateField(blank=True, null=True, verbose_name="effective to")), ("is_default", models.BooleanField(default=False, verbose_name="default")), ("output_mapping", models.JSONField(blank=True, default=dict, verbose_name="output mapping")), ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="published at")),
            ("archived_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_archived_by", to=settings.AUTH_USER_MODEL, verbose_name="Archived by")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Created by")), ("published_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="published_financial_document_templates", to=settings.AUTH_USER_MODEL, verbose_name="published by")), ("record_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="document_templates", to="configuration.financialrecordtype", verbose_name="record type")), ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Updated by")),
        ], options={"ordering": ["record_type", "-version"]}),
        migrations.CreateModel(name="FinancialDocumentTemplateField", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")), ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")), ("is_archived", models.BooleanField(default=False, verbose_name="Archived")), ("archived_at", models.DateTimeField(blank=True, null=True, verbose_name="Archived at")),
            ("key", models.CharField(max_length=60, verbose_name="key")), ("label", models.CharField(max_length=120, verbose_name="label")), ("data_type", models.CharField(choices=[("string", "Text (single line)"), ("text", "Text (multi line)"), ("integer", "Whole number"), ("decimal", "Decimal number"), ("boolean", "Yes / No"), ("date", "Date"), ("choice", "Single choice"), ("multi_choice", "Multiple choice"), ("email", "Email"), ("url", "URL")], default="string", max_length=20, verbose_name="field type")), ("is_required", models.BooleanField(default=False, verbose_name="required")), ("display_order", models.PositiveIntegerField(default=0, verbose_name="display order")), ("section", models.CharField(blank=True, max_length=100, verbose_name="section")), ("help_text", models.TextField(blank=True, verbose_name="help text")), ("default_value", models.JSONField(blank=True, null=True, verbose_name="default value")), ("choices", models.JSONField(blank=True, default=list, verbose_name="choices")), ("max_length", models.PositiveIntegerField(blank=True, null=True, verbose_name="maximum length")), ("validation", models.JSONField(blank=True, default=dict, verbose_name="validation")), ("output_mapping", models.JSONField(blank=True, default=dict, verbose_name="output mapping")), ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ("archived_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_archived_by", to=settings.AUTH_USER_MODEL, verbose_name="Archived by")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created", to=settings.AUTH_USER_MODEL, verbose_name="Created by")), ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="fields", to="financial_records.financialdocumenttemplate", verbose_name="template")), ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated", to=settings.AUTH_USER_MODEL, verbose_name="Updated by")),
        ], options={"ordering": ["display_order", "key"]}),
        migrations.AddField(model_name="financialrecord", name="template_snapshot", field=models.JSONField(blank=True, default=dict, help_text="Immutable schema snapshot retained for historical interpretation.", verbose_name="template snapshot")),
        migrations.AddField(model_name="financialrecord", name="template", field=models.ForeignKey(blank=True, help_text="Published template version used when this record was created.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="financial_records", to="financial_records.financialdocumenttemplate", verbose_name="document template")),
        migrations.AddIndex(model_name="financialdocumenttemplate", index=models.Index(fields=["record_type", "status"], name="fdt_type_status_idx")), migrations.AddConstraint(model_name="financialdocumenttemplate", constraint=models.UniqueConstraint(fields=("record_type", "version"), name="fdt_unique_type_version")), migrations.AddConstraint(model_name="financialdocumenttemplate", constraint=models.UniqueConstraint(condition=models.Q(is_archived=False, is_default=True, status="published"), fields=("record_type",), name="fdt_one_default_published")), migrations.AddIndex(model_name="financialdocumenttemplatefield", index=models.Index(fields=["template", "display_order"], name="fdtf_template_order_idx")), migrations.AddConstraint(model_name="financialdocumenttemplatefield", constraint=models.UniqueConstraint(fields=("template", "key"), name="fdtf_unique_template_key")),
    ]
