# Generated by Django 6.0 on 2026-08-26 21:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashtransfer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AddField(
            model_name="cashtransfer",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated by",
            ),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="amount",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.0000"), max_digits=18, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Archived at"),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_archived_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Archived by",
            ),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="is_archived",
            field=models.BooleanField(default=False, verbose_name="Archived"),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="reference",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Reference"
            ),
        ),
        migrations.AlterField(
            model_name="cashtransfer",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
