# Generated by Django 6.0 on 2026-08-27 14:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0004_company_custom_fields"),
        ("parties", "0002_client_kind"),
        ("transfers", "0002_align_cashtransfer_with_tracked_base"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityOpeningBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("is_archived", models.BooleanField(default=False, verbose_name="Archived")),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Archived at"),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("associated_person", "Associated Person"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="entity type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Signed starting balance. Negative means the entity starts in deficit.",
                        max_digits=18,
                        verbose_name="opening amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="MAD", max_length=3, verbose_name="currency"),
                ),
                (
                    "as_of_date",
                    models.DateField(
                        help_text="Date this starting position is effective from.",
                        verbose_name="as of date",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_archived_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archived by",
                    ),
                ),
                (
                    "associated_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_opening_balances",
                        to="parties.associatedperson",
                        verbose_name="associated person",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_opening_balances",
                        to="companies.company",
                        verbose_name="company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "entity opening balance",
                "verbose_name_plural": "entity opening balances",
                "ordering": ["entity_type", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("company__isnull", False)),
                        fields=("company", "currency"),
                        name="opening_balance_unique_company_currency",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("associated_person__isnull", False)),
                        fields=("associated_person", "currency"),
                        name="opening_balance_unique_person_currency",
                    ),
                ],
            },
        ),
    ]
